import re

with open('demo/index.html', encoding='utf-8') as f:
    content = f.read()

new_arch = (
    '\n'
    '        <!-- Preprocessing -->\n'
    '        <div>\n'
    '          <h3 class="text-xs font-semibold uppercase tracking-widest text-[#8b949e] mb-4">Common Preprocessing</h3>\n'
    '          <div class="flex flex-wrap items-center gap-2 text-xs">\n'
    '            <span class="bg-[#21262d] border border-[#30363d] rounded px-3 py-2 text-center"><span class="text-[#e6edf3] block">.npy / .csv</span><span class="text-[#8b949e]">input file</span></span>\n'
    '            <span class="text-[#818cf8] text-lg">&#x2192;</span>\n'
    '            <span class="bg-[#21262d] border border-[#30363d] rounded px-3 py-2 text-center"><span class="text-[#e6edf3] block">Shape check</span><span class="text-[#8b949e]">[12&times;1000] or [1000&times;12]</span></span>\n'
    '            <span class="text-[#818cf8] text-lg">&#x2192;</span>\n'
    '            <span class="bg-[#21262d] border border-[#30363d] rounded px-3 py-2 text-center"><span class="text-[#e6edf3] block">Pad / trim</span><span class="text-[#8b949e]">&rarr; 1000 samples</span></span>\n'
    '            <span class="text-[#818cf8] text-lg">&#x2192;</span>\n'
    '            <span class="bg-[#21262d] border border-[#30363d] rounded px-3 py-2 text-center"><span class="text-[#e6edf3] block">Z-score norm</span><span class="text-[#8b949e]">per-lead &middot; &mu;=0 &sigma;=1</span></span>\n'
    '            <span class="text-[#818cf8] text-lg">&#x2192;</span>\n'
    '            <span class="bg-[#0f3d2e] border border-emerald-800 rounded px-3 py-2 text-center"><span class="text-emerald-300 font-mono block">1 &times; 12 &times; 1000</span><span class="text-[#8b949e]">float32 tensor</span></span>\n'
    '          </div>\n'
    '        </div>\n'
    '        <!-- Model architectures -->\n'
    '        <div>\n'
    '          <h3 class="text-xs font-semibold uppercase tracking-widest text-[#8b949e] mb-4">Model Architectures</h3>\n'
    '          <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">\n'
    '            <!-- RetNet -->\n'
    '            <div class="bg-[#21262d] rounded-lg border border-[#30363d] p-4">\n'
    '              <div class="flex items-center gap-2 mb-3">\n'
    '                <span class="w-2.5 h-2.5 rounded-full flex-shrink-0" style="background:#818cf8"></span>\n'
    '                <span class="text-sm font-semibold text-white">RetNet</span>\n'
    '                <span class="ml-auto text-xs text-[#8b949e]">33.5 M &middot; AUROC 0.913</span>\n'
    '              </div>\n'
    '              <div class="space-y-1.5 text-xs">\n'
    '                <div class="flex items-center gap-2"><span style="color:#818cf8">&#x25b8;</span><span class="text-[#e6edf3]">MultiScalePatchEmbed</span><span class="ml-auto text-[#6e7681]">k=5/11/25</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#818cf8">&#x25b8;</span><span class="text-[#e6edf3]">MultiScaleRetention &times;10</span><span class="ml-auto text-[#6e7681]">H=8, xPos</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#818cf8">&#x25b8;</span><span class="text-[#e6edf3]">RetNetFFN &times;10</span><span class="ml-auto text-[#6e7681]">SwiGLU &middot; DropPath</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#818cf8">&#x25b8;</span><span class="text-[#e6edf3]">LeadFusionTransformer</span><span class="ml-auto text-[#6e7681]">2-layer cross-lead</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#818cf8">&#x25b8;</span><span class="text-[#e6edf3]">Classifier</span><span class="ml-auto text-[#6e7681]">GAP &rarr; Linear &rarr; 5</span></div>\n'
    '              </div>\n'
    '            </div>\n'
    '            <!-- InceptionTime -->\n'
    '            <div class="bg-[#21262d] rounded-lg border border-[#30363d] p-4">\n'
    '              <div class="flex items-center gap-2 mb-3">\n'
    '                <span class="w-2.5 h-2.5 rounded-full flex-shrink-0" style="background:#06b6d4"></span>\n'
    '                <span class="text-sm font-semibold text-white">InceptionTime</span>\n'
    '                <span class="ml-auto text-xs text-[#8b949e]">~3 M &middot; AUROC 0.907</span>\n'
    '              </div>\n'
    '              <div class="space-y-1.5 text-xs">\n'
    '                <div class="flex items-center gap-2"><span style="color:#06b6d4">&#x25b8;</span><span class="text-[#e6edf3]">InceptionModule &times;6</span><span class="ml-auto text-[#6e7681]">k=10/20/40</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#06b6d4">&#x25b8;</span><span class="text-[#e6edf3]">Bottleneck Conv 1&times;1</span><span class="ml-auto text-[#6e7681]">dim reduction</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#06b6d4">&#x25b8;</span><span class="text-[#e6edf3]">Residual shortcuts</span><span class="ml-auto text-[#6e7681]">every 3 blocks</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#06b6d4">&#x25b8;</span><span class="text-[#e6edf3]">Global Avg Pool</span><span class="ml-auto text-[#6e7681]">temporal squeeze</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#06b6d4">&#x25b8;</span><span class="text-[#e6edf3]">Classifier</span><span class="ml-auto text-[#6e7681]">Linear &rarr; 5</span></div>\n'
    '              </div>\n'
    '            </div>\n'
    '            <!-- SE Attention -->\n'
    '            <div class="bg-[#21262d] rounded-lg border border-[#30363d] p-4">\n'
    '              <div class="flex items-center gap-2 mb-3">\n'
    '                <span class="w-2.5 h-2.5 rounded-full flex-shrink-0" style="background:#fbbf24"></span>\n'
    '                <span class="text-sm font-semibold text-white">SE Attention</span>\n'
    '                <span class="ml-auto text-xs text-[#8b949e]">~5 M &middot; AUROC 0.906</span>\n'
    '              </div>\n'
    '              <div class="space-y-1.5 text-xs">\n'
    '                <div class="flex items-center gap-2"><span style="color:#fbbf24">&#x25b8;</span><span class="text-[#e6edf3]">Per-lead ResNet1d encoder</span><span class="ml-auto text-[#6e7681]">shared weights</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#fbbf24">&#x25b8;</span><span class="text-[#e6edf3]">SE blocks</span><span class="ml-auto text-[#6e7681]">channel attention</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#fbbf24">&#x25b8;</span><span class="text-[#e6edf3]">Cross-lead attention pool</span><span class="ml-auto text-[#6e7681]">12 leads &rarr; 1</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#fbbf24">&#x25b8;</span><span class="text-[#e6edf3]">Super-pooling</span><span class="ml-auto text-[#6e7681]">attn + max + mean</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#fbbf24">&#x25b8;</span><span class="text-[#e6edf3]">Classifier</span><span class="ml-auto text-[#6e7681]">Linear &rarr; 5</span></div>\n'
    '              </div>\n'
    '            </div>\n'
    '            <!-- LeadWise GNN -->\n'
    '            <div class="bg-[#21262d] rounded-lg border border-[#30363d] p-4">\n'
    '              <div class="flex items-center gap-2 mb-3">\n'
    '                <span class="w-2.5 h-2.5 rounded-full flex-shrink-0" style="background:#f43f5e"></span>\n'
    '                <span class="text-sm font-semibold text-white">LeadWise GNN</span>\n'
    '                <span class="ml-auto text-xs text-[#8b949e]">~2 M &middot; AUROC 0.912</span>\n'
    '              </div>\n'
    '              <div class="space-y-1.5 text-xs">\n'
    '                <div class="flex items-center gap-2"><span style="color:#f43f5e">&#x25b8;</span><span class="text-[#e6edf3]">Per-lead ResNet1d</span><span class="ml-auto text-[#6e7681]">12 embeddings</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#f43f5e">&#x25b8;</span><span class="text-[#e6edf3]">Clinical adj. graph</span><span class="ml-auto text-[#6e7681]">12 nodes / ECG anatomy</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#f43f5e">&#x25b8;</span><span class="text-[#e6edf3]">Graph Attention (GAT)</span><span class="ml-auto text-[#6e7681]">2 layers</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#f43f5e">&#x25b8;</span><span class="text-[#e6edf3]">Global mean pool</span><span class="ml-auto text-[#6e7681]">graph &rarr; vector</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#f43f5e">&#x25b8;</span><span class="text-[#e6edf3]">Classifier</span><span class="ml-auto text-[#6e7681]">Linear &rarr; 5</span></div>\n'
    '              </div>\n'
    '            </div>\n'
    '            <!-- ResNet1d -->\n'
    '            <div class="bg-[#21262d] rounded-lg border border-[#30363d] p-4">\n'
    '              <div class="flex items-center gap-2 mb-3">\n'
    '                <span class="w-2.5 h-2.5 rounded-full flex-shrink-0" style="background:#a3a3a3"></span>\n'
    '                <span class="text-sm font-semibold text-white">ResNet1d</span>\n'
    '                <span class="ml-auto text-xs text-[#8b949e]">~1 M &middot; AUROC 0.905</span>\n'
    '              </div>\n'
    '              <div class="space-y-1.5 text-xs">\n'
    '                <div class="flex items-center gap-2"><span style="color:#a3a3a3">&#x25b8;</span><span class="text-[#e6edf3]">Conv1d stem</span><span class="ml-auto text-[#6e7681]">k=15, 64 ch</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#a3a3a3">&#x25b8;</span><span class="text-[#e6edf3]">ResidualBlock1d &times;3</span><span class="ml-auto text-[#6e7681]">64&rarr;128&rarr;256</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#a3a3a3">&#x25b8;</span><span class="text-[#e6edf3]">Concat pool</span><span class="ml-auto text-[#6e7681]">avg + max</span></div>\n'
    '                <div class="flex items-center gap-2"><span style="color:#a3a3a3">&#x25b8;</span><span class="text-[#e6edf3]">Classifier</span><span class="ml-auto text-[#6e7681]">Linear &rarr; 5</span></div>\n'
    '              </div>\n'
    '            </div>\n'
    '          </div>\n'
    '        </div>\n'
)

result = re.sub(r'(?s)\s*<!-- inline architecture SVG.*?</svg>', new_arch, content)

if result == content:
    print('ERROR: pattern not found')
else:
    with open('demo/index.html', 'w', encoding='utf-8') as f:
        f.write(result)
    print('OK: architecture section replaced')
